export const EVENTS = {
    COMPONENT_INIT: 'COMPONENT_INIT',
    COMPONENT_DID_MOUNT: 'COMPONENT_DID_MOUNT',
    COMPONENT_RENDER: 'COMPONENT_RENDER',
    COMPONENT_DID_UPDATE: 'COMPONENT_DID_UPDATE',
}
